### ISSUE TITLE
ncpu error in  pyxis

### ISSUE THREAD

**Issue by andferrari** [SpheMakh/HI-Inator#8]
Hi,
thank you for your awesome work!

Since the commits on Aug 28, 2015  HI-inator crashes with:

```
Traceback (most recent call last):
  File "/code/depends/pyxis/Pyxis/bin/pyxis", line 295, in <module>
    Pyxis.Internals.run(*commands);
  File "/code/depends/pyxis/Pyxis/Internals.py", line 1099, in run
    comcall();
  File "./pyxis-hikat.py", line 169, in azishe
    ncpu = params["ncpu"]
KeyError: 'ncpu'
2015/09/08 20:01:11 ERROR: Exception raised, aborting
```

The previous version works perfectly.

**Comment by sphemakh** [comment]
I forgot to update the config file after adding a new feature. It should work again now.
